-- Legacy entry point retained for existing bookmarks.
-- The former workbook queried raw direct identifiers and private OLT addresses.
-- Use sql/powerbi_star_schema.sql for the privacy-safe production model.
