table dim_date
	lineageTag: f680d067-e0ca-41e5-98a7-ef1a0432d3ae

	column date
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: dc213de2-a442-4c5f-b89a-c3ac9c546102
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column date_key
		dataType: int64
		lineageTag: 911a34a3-b4e5-4058-a394-c922bd73f1a6
		summarizeBy: none
		sourceColumn: date_key

	column year
		dataType: int64
		lineageTag: 2046988f-7fe7-4dba-b97e-49baba8897bb
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		lineageTag: bf2c1507-0c57-4849-8a14-7ef2c042c77e
		summarizeBy: none
		sourceColumn: quarter

	column month_number
		dataType: int64
		lineageTag: 9819075b-b1c7-46ee-9a1b-aa5998bef18b
		summarizeBy: none
		sourceColumn: month_number

	column month_name
		dataType: string
		lineageTag: cfc7241f-712d-42aa-bf71-d640ae203bf6
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		lineageTag: 6c98b3ac-ed0c-4717-ab71-ad5d911ffd5b
		summarizeBy: none
		sourceColumn: year_month

	column week_start
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: a98969a2-82da-4d19-8f89-2cfdb01a514a
		summarizeBy: none
		sourceColumn: week_start

		annotation UnderlyingDateTimeDataType = Date

	column is_future_at_extract
		dataType: boolean
		lineageTag: 4db74814-c7a1-41b4-aeba-da99dc0ac1a9
		summarizeBy: none
		sourceColumn: is_future_at_extract

	partition dim_date = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataRoot & "dim_date.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers,"",null,Replacer.ReplaceValue,Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls,{{"date", type date},{"date_key", Int64.Type},{"year", Int64.Type},{"quarter", type text},{"month_number", Int64.Type},{"month_name", type text},{"year_month", type text},{"week_start", type date},{"is_future_at_extract", type logical}},"en-US")
				in Typed

